import PDFDocument from 'pdfkit';
import type { AdminReport } from './crystalBioBackend';

const moneySafeText = (value: unknown) => String(value ?? '').replace(/[\r\n]+/g, ' ').trim();

export function renderAdminReportPdf(report: AdminReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.font('Helvetica-Bold').fontSize(20).fillColor('#243225').text('Crystal Bio Field Report');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#5d6a5f').text(`Report period: ${report.fromDate} to ${report.toDate}`);
    doc.moveDown(1);

    doc.font('Helvetica-Bold').fontSize(13).fillColor('#243225').text('Quick summary');
    doc.moveDown(0.4);
    const summaryRows = [
      ['Checked-in agents', report.totals.checkedInAgents],
      ['Checked-out agents', report.totals.checkedOutAgents],
      ['Sales visits', report.totals.salesVisits],
      ['Service visits', report.totals.serviceVisits],
      ['Pending leave requests', report.totals.pendingLeaveRequests],
    ];
    summaryRows.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#3b4a3d').text(`${label}: `, { continued: true });
      doc.font('Helvetica').fillColor('#243225').text(String(value));
    });
    doc.moveDown(1);

    doc.font('Helvetica-Bold').fontSize(13).fillColor('#243225').text('Person-wise work summary');
    doc.moveDown(0.4);
    if (report.agentSummaries.length === 0) {
      doc.font('Helvetica').fontSize(10).fillColor('#5d6a5f').text('No agent activity found for this date range.');
    }
    report.agentSummaries.forEach((agent, index) => {
      if (doc.y > 710) doc.addPage();
      doc.roundedRect(48, doc.y, 500, 74, 8).strokeColor('#d9e2d6').lineWidth(1).stroke();
      const startY = doc.y + 10;
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#243225').text(`${index + 1}. ${moneySafeText(agent.agentName)}`, 62, startY);
      doc.font('Helvetica').fontSize(9).fillColor('#5d6a5f').text(`Attendance: ${agent.attendanceStatus.replace(/_/g, ' ')}`, 62, startY + 18);
      doc.text(`Sales visits: ${agent.salesVisitCount}   Service visits: ${agent.serviceVisitCount}`, 62, startY + 34);
      const followUps = agent.followUpsDue.length ? agent.followUpsDue.join(', ') : 'None';
      doc.text(`Follow-ups due: ${moneySafeText(followUps)}`, 62, startY + 50, { width: 460 });
      doc.y = startY + 82;
    });

    if (doc.y > 650) doc.addPage();
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').fontSize(13).fillColor('#243225').text('Needs office action');
    doc.moveDown(0.4);
    if (report.followUpsDue.length === 0 && report.totals.pendingLeaveRequests === 0) {
      doc.font('Helvetica').fontSize(10).fillColor('#5d6a5f').text('No urgent office action found for this report period.');
    } else {
      if (report.totals.pendingLeaveRequests > 0) {
        doc.font('Helvetica').fontSize(10).fillColor('#243225').text(`• ${report.totals.pendingLeaveRequests} leave request(s) pending review.`);
      }
      report.followUpsDue.forEach((item) => doc.font('Helvetica').fontSize(10).fillColor('#243225').text(`• ${moneySafeText(item)}`));
    }

    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i += 1) {
      doc.switchToPage(i);
      doc.font('Helvetica').fontSize(8).fillColor('#8a948b').text(`Generated by Crystal Bio Field Hub • Page ${i + 1} of ${pageCount}`, 48, 790, {
        align: 'center',
        width: 500,
      });
    }

    doc.end();
  });
}
